import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Mi Portafolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
       className="bg-[#D5C6B4]"
      >
        {children}
      </body>
    </html>
  );
}
